### ISSUE TITLE
Can I use pynvme for ubuntu 16.04 or 18.04?

### ISSUE THREAD

**Issue by wenjingren** [cranechu/pynvme#10]
Can I use pynvme for ubuntu 16.04 or 18.04?

**Comment by cranechu** [comment]
In release [v19.02.1](https://github.com/cranechu/pynvme/releases/tag/v19.02.1), I tested pynvme in Ubuntu 18.04. It worked. But I have only resource to run CI tests in Fedora 29. Recently, my friends reported problems in Ubuntu 18.04 due to Python's new f-string feature. If you like to solve that problems, PRs are always welcome!  :)

**Comment by wenjingren** [comment]
ok，let me try.

**Comment by cranechu** [comment]
Tested pynvme 1.0 in Ubuntu 18.04,2 LTS, with Python 3.6.8 (by default).
