### ISSUE TITLE
pynvme usage

### ISSUE THREAD

**Issue by chens54** [cranechu/pynvme#24]
1. I noticed that we can get admin command response by hook an callback funtion, but I saw the parameters are dw0 and status, how could I get other dw values in completion tree?
2. Could I abort an command with specified CID? abort implemented in pynvme is calling which library?
3. How could I parse buffer? smart_log.data(3, 1), what does 3 and 1 indicates?

**Comment by cranechu** [comment]
1. In callback function, pynvme only provides dw0 and status. You can find other completion dw values in qpairs' cmdlog (e.g. with vscode plugin), but it is designed for human instead of scripts. 

2. You can call method Controller.abort(self, cid, sqid, cb). It is implemented by calling SPDK, which is just the same as others NVMe commands. 

3. please refer to python doc: https://github.com/cranechu/pynvme#data . In VSCode, the help docstring will be displayed automatically, look like this pictures: ![](https://github.com/cranechu/pynvme/raw/master/doc/pic/docstring.png)

Thanks, 
-Crane
