### ISSUE TITLE
NVMe Command return status variable contains Phase Tag value

### ISSUE THREAD

**Issue by FolandZhang** [cranechu/pynvme#27]
File a bug as a record for NVme CQE status variable issue.

When I get NVMe command return status field value, found status is always wrong, after confirm with Crane, CQE "status" variable contains Phase Tag indeed in pyNVMe code.

So, need workaround for high level function to ((status >> 1) & 0x7fff) for only getting Status Field Value.

Thanks a lot!

**Comment by cranechu** [comment]
Pynvme driver provides two arguments to python callback functions: cdw0 of the Completion Queue Entry, and the status. The argument status includes both Phase Tag and Status Field.

The design exists since v1.0, so we have to keep it to avoid scripts modification. 

So, we will not make any change for that, and the status in command callback function is 16-bit value including both phase-bit and other status information.
